<?php
return [
    'name' => 'VARCHAR(100) DEFAULT NULL',
    'username' => 'VARCHAR(100) DEFAULT NULL',
    'traderId' => 'VARCHAR(50) DEFAULT NULL',
    'verified' => 'VARCHAR(10) DEFAULT NULL',
    'emailVerified' => 'VARCHAR(10) DEFAULT NULL',
    'smsVerified' => 'VARCHAR(10) DEFAULT NULL',
    'idVerified' => 'VARCHAR(10) DEFAULT NULL',
    'topSeller' => 'VARCHAR(10) DEFAULT NULL',
    'completion' => 'VARCHAR(10) DEFAULT NULL',
    'orders' => 'INT(11) DEFAULT 0',
    'price' => 'VARCHAR(50) DEFAULT NULL',
    'limits' => 'VARCHAR(50) DEFAULT NULL',
    'quantity' => 'VARCHAR(50) DEFAULT NULL',
    'avgRelease' => 'VARCHAR(50) DEFAULT NULL',
    'payment' => 'TEXT DEFAULT NULL',
    'country' => 'VARCHAR(10) DEFAULT NULL',
    'status' => 'VARCHAR(50) DEFAULT NULL',
    'lastActive' => 'VARCHAR(50) DEFAULT NULL',
    'adType' => 'VARCHAR(20) DEFAULT NULL',
    'createdAt' => 'VARCHAR(50) DEFAULT NULL',
    'updatedAt' => 'VARCHAR(50) DEFAULT NULL',
];
