<?php
DEFINE('ipAddress', 'http://192.168.1.238/');
DEFINE('RegTable', 'registertable');
DEFINE('admintable', 'admintable');
DEFINE('EmailValidation', 'emailvalidation');
DEFINE('forgotPass', 'forgottenpass'); 
DEFINE('advancedVerification', 'advancedVerification');
DEFINE('disabledAccount', 'disabledAccount');
DEFINE('idVer', 'idVerification');
DEFINE('kyc', 'kyc');
DEFINE('messagenoti', 'messagenoti');
DEFINE('wallet', 'coin_wallets'); 
DEFINE('refresh_token', 'refresh_token'); 
DEFINE('sitelink', ipAddress.':5173/'); 
DEFINE('apiLink', ipAddress.'cashtradeproApi/'); 
DEFINE('appLink', ipAddress.':5173/'); 
DEFINE('siteaddress', '7JR7+F94, George Town, Cayman Islands');
DEFINE('sitenumber', '1(652)59444448');
DEFINE('sitename', 'Cash Trade Pro');
DEFINE('sitemail', 'support@cashtradepro.com');
define('SMTP_DSN', 'smtp://mailing@cashtradepro.com:8&hf6%C]_ER{@c8.my-control-panel.com:465');
define('emailLogo', ipAddress.'cashtradeproApi/image/logo.png');
